services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight Web UI
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # RedisInsight standalone (alternativa mais leve)
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8002:8001"
    depends_on:
      - redis-stack
    restart: unless-stopped
    environment:
      - REDISINSIGHT_HOST=redis-stack
      - REDISINSIGHT_PORT=6379

volumes:
  redis_data:
    driver: local
